- src/rules/requireReturnType.js
- tests/rules/assertions/requireReturnType.js
PR to allow 'void' in place of 'undefined'.
> Use 'void' and 'undefined' interchangeably

- README.md
- src/rules/requireParameterType.js
- src/rules/requireReturnType.js
- src/utilities/index.js
- src/utilities/isFlowFile.js
- tests/rules/assertions/requireParameterType.js
- tests/rules/assertions/requireReturnType.js
Fixes https://github.com/gajus/eslint-plugin-flowtype/issues/5
> Add a 'flow' option that only checks files annotated @flow

- .README/rules/type-id-match.md
- README.md
- bin/readmeAssertions.js
- src/rules/typeIdMatch.js
- tests/rules/assertions/typeIdMatch.js
Corrected a mistake regarding type aliases
> Fixes to README

- README.md
- src/rules/requireReturnType.js
- tests/rules/assertions/requireReturnType.js
> Correct undefined for async & generator functions

- README.md
- src/rules/requireParameterType.js
- tests/rules/assertions/requireParameterType.js
> Allow excluding arrow functions from require-param

- .README/rules/space-after-type-colon.md
- .README/rules/space-before-type-colon.md
- README.md
- src/rules/spaceAfterTypeColon.js
- src/rules/spaceBeforeTypeColon.js
- src/utilities/index.js
- src/utilities/spacingFixers.js
- tests/rules/assertions/spaceAfterTypeColon.js
- tests/rules/assertions/spaceBeforeTypeColon.js
These rules are now auto-fixable with ESLint's `--fix` 😃
> Autofix for space-before/space-after

- README.md
- src/rules/spaceAfterTypeColon.js
- src/rules/spaceBeforeTypeColon.js
- src/utilities/getParameterName.js
- tests/rules/assertions/spaceAfterTypeColon.js
- tests/rules/assertions/spaceBeforeTypeColon.js
See #63.
Also added tests for classes for static properties, just to be sure they worked.
> Handle declare class with static properties

- src/rules/spaceAfterTypeColon.js
- tests/rules/assertions/spaceAfterTypeColon.js
see: https://github.com/gajus/eslint-plugin-flowtype/issues/27#issuecomment-241531712
> Fix optional FunctionTypeParam space-after-colon

- .README/README.md
- .README/rules/boolean-style.md
- src/index.js
- src/rules/booleanStyle.js
- tests/rules/assertions/booleanStyle.js
- tests/rules/index.js
> feat: new boolean-style rule

- src/rules/spaceAfterTypeColon.js
- src/rules/spaceBeforeTypeColon.js
- src/utilities/getParameterName.js
- tests/rules/assertions/spaceAfterTypeColon.js
- tests/rules/assertions/spaceBeforeTypeColon.js
> feat: Add variance support to spaceBeforeTypeColon & spaceAfterTypeColon

- src/rules/spaceAfterTypeColon.js
- src/rules/spaceBeforeTypeColon.js
- src/rules/unionIntersectionSpacing.js
- src/utilities/getTokenAfterParens.js
- src/utilities/getTokenBeforeParens.js
- src/utilities/index.js
- tests/rules/assertions/spaceAfterTypeColon.js
- tests/rules/assertions/spaceBeforeTypeColon.js
closes #134
bunch of duplication, but another PR will handle that.
> feat: ObjectTypeIndexer in spaceBeforeTypeColon & spaceAfterTypeColon

- .README/rules/space-after-type-colon.md
- src/rules/spaceAfterTypeColon.js
- src/rules/typeColonSpacing/reporter.js
- tests/rules/assertions/spaceAfterTypeColon.js
This PR allows a line break to satisfy the trailing space requirement as per issue #31.
> feat: allow line break to satisfy trailing space rule (fixes #31)

- src/rules/typeColonSpacing/reporter.js
- tests/rules/assertions/spaceAfterTypeColon.js
- tests/rules/assertions/spaceBeforeTypeColon.js
https://github.com/gajus/eslint-plugin-flowtype/issues/145
https://github.com/babel/babylon/pull/197
> feat: support optional Flow names (closes #145)

- src/rules/noTypesMissingFileAnnotation.js
- tests/rules/assertions/noTypesMissingFileAnnotation.js
> Add type re-export support to no-types-missing-file-annotation

- .README/README.md
> Adds eslint-config-flowtype-essential

- src/rules/typeColonSpacing/evaluateVariables.js
- src/rules/typeColonSpacing/index.js
- tests/rules/assertions/spaceAfterTypeColon.js
- tests/rules/assertions/spaceBeforeTypeColon.js
This PR adds a VariableDeclaration hook to before / after colon spacing checks. 
Fixes issue #178.
> feat: add variable declarations to colon spacing checks (fixes #178)

- README.md
- src/rules/requireReturnType.js
- tests/rules/assertions/requireReturnType.js
> feat(require-return-type): add annotateUndefined: 'ignore' option

- README.md
- src/rules/requireInexactType.js
- tests/rules/assertions/requireInexactType.js
> fix: interfaces and classes

- src/rules/useFlowType.js
- tests/rules/assertions/useFlowType.js
> fix: no-unused-vars with with default type in GenericType

- .travis.yml
- package.json
- src/rules/booleanStyle.js
- src/rules/genericSpacing.js
- src/rules/newlineAfterFlowAnnotation.js
- src/rules/requireValidFileAnnotation.js
- src/rules/sortKeys.js
- src/rules/spaceBeforeGenericBracket.js
- src/rules/typeColonSpacing/evaluateObjectTypeProperty.js
- src/rules/typeColonSpacing/reporter.js
- src/rules/unionIntersectionSpacing.js
- src/utilities/spacingFixers.js
- tests/rules/assertions/arrayStyleSimpleType.js
- tests/rules/assertions/defineFlowType.js
- tests/rules/assertions/requireIndexerName.js
- tests/rules/assertions/requireValidFileAnnotation.js
- tests/rules/assertions/sortKeys.js
- tests/rules/assertions/useFlowType.js
BREAKING CHANGE: Requires Node@^10.12.x || 12.x
BREAKING CHANGE: Requires ESLint@^7.x
Closes #446
> feat: Support ESLint 7.x

- .README/rules/no-unused-expressions.md
- src/rules/noUnusedExpressions.js
- tests/rules/assertions/noUnusedExpressions.js
> fix: false positive for optional call expressions in no-unused-expressions

- src/rules/genericSpacing.js
This must've happened when merging all the previous PRs in one go
> fix: remove duplicate meta usage

- .gitignore
> chore: Should ignore yarn.lock not yack.lock
