gajus/eslint-plugin-flowtype

src/utilities/getParameterName.js, tests/rules/assertions/requireParameterType.js
Here's a quick fix for #6 .
I added an "invalid" fixture but wasn't able to create a "valid" fixture.
My valid fixture was: `({foo = 1}: {foo: number} = {}) => {}'` which raises the following error:
```
AssertionError: Should have no errors but had 1: [ { ruleId: null,
fatal: true,
severity: 2,
source: '({foo = 1}: {foo: number} = {}) => {}',
message: 'Parsing error: Binding rvalue',
line: 1,
column: 2 } ]
```
There were a couple of errors and warnings when linting the plugin itself (`npm run lint`), but none of these were introduced by this patch so I decided to ignore them.
=> fix #6: destructuring with a default parameter

src/rules/spaceAfterTypeColon.js, tests/rules/assertions/spaceAfterTypeColon.js
Given the following configuration:
```json
"flowtype/space-after-type-colon": [
1,
"never"
]
```
and a function:
```js
function fn (key: string): Object {
```
Running the linter will produce the following:
> xxx:yy  warning  There must be no space after "key" parameter type annotation colon  flowtype/space-after-type-colon
This patch will address this issue and ensure that the return type is also taken into consideration when checking for spaces after the colon.
=> issue 11: space-after-type-colon does not apply to the return type

src/rules/requireReturnType.js, tests/rules/assertions/requireReturnType.js
An arrow function can be written shorthand like so:
```
(foo) => "foo"
```
This was improperly being recognized as not returning a value. This will check to see if the arrow function is an expression and if it is, will be assumed to be returning something.
---
Before the node's return type was deemed undefined if it had one of the following:
- `typeAnnotation` of `VoidTypeAnnotation`
- `typeAnnotation` of `GenericTypeAnnotation`
That will produce false positives because a `typeAnnotation` of `GenericTypeAnnotation` can be things other than `undefined`. This will check for a `GenericTypeAnnotation` that is actually `undefined`.
Closes #15
=> Properly handle arrow function expressions and generic return type annotations

.README/README.md, .README/rules/require-valid-file-annotation.md, README.md, src/index.js, src/rules/requireValidFileAnnotation.js, src/utilities/index.js, src/utilities/isFlowFile.js, src/utilities/isFlowFileAnnotation.js, tests/rules/assertions/requireValidFileAnnotation.js, tests/rules/index.js
A new rule to check for typos or placement error of the `// @flow` comment.
Even if I know the rule, I keep inadvertently inserting the `/*eslint ...*/` comment or `"use strict"` at the beginning of the file, disabling the flow check, and nothing is warning me about this. I think it would be a great addition to this plugin.
I'm open to discussion: you can consider this as a proposal and a prototype implementation.
PS: I love the `readmeAssertions.js` script! great idea.
PPS: You should commit the .eslintrc you are using for this project.
=> require-valid-file-annotation rule implementation

README.md, src/rules/spaceAfterTypeColon.js, tests/rules/assertions/spaceAfterTypeColon.js
Fixes #32 
Matching of compound types `(number|string)` was broken too, now it works.
=> Fix space-after-type-colon false-positive on return of function types.

README.md, src/rules/spaceBeforeTypeColon.js, tests/rules/assertions/spaceBeforeTypeColon.js
Just allowing an additional character (the `?`) when the type is optional.
```js
(foo?: string) => {}
```
=> Support for Optional Args in spaceBeforeTypeColon

src/rules/spaceBeforeTypeColon.js, tests/rules/assertions/spaceAfterTypeColon.js, tests/rules/assertions/spaceBeforeTypeColon.js
Currently the `space-before-type-colon` rule only works for arrow functions. It seems the current implementation is actually based off a parsing bug: https://github.com/babel/babylon/issues/51 - for normal functions, the parameter locations include the type annotations, but they don't for arrow functions.
It now works for both normal functions and arrow functions (and should continue working if that bug is fixed). I've also added a few more tests to `space-after-type-colon` just to be sure it works.
Fixes #20.
=> Fix "space-before-type-colon" for non-arrow functions

README.md, src/rules/requireReturnType.js, tests/rules/assertions/requireReturnType.js
Realised I messed up with #49 - sorry!
It would not error on an async/generator function missing a return type.
Cleaned up the implementation a little so `isFunctionReturnUndefined` can't be true if it's a async/generator function (as they'd return at least a Promise or Generator)
=> Fix where async func would not require return type

.README/rules/require-parameter-type.md, .README/rules/require-return-type.md, README.md, src/rules/requireParameterType.js, src/rules/requireReturnType.js, tests/rules/assertions/requireParameterType.js, tests/rules/assertions/requireReturnType.js
* adds option for arrow functions to skip return types: https://github.com/gajus/eslint-plugin-flowtype/commit/866605b63f6b4092ee95d73288788083fc782d9d
* replicates the `{ "excludeArrowFunctions": true }` option for param types in #50
* adds option for only arrow function _expressions_ to skip return type: https://github.com/gajus/eslint-plugin-flowtype/commit/b09b85d2f4138c383d480ea9e4db10f599851cbb
* can use `{ "excludeArrowFunctions": "expressionsOnly" }` on return types
* adds option for only arrow function _expressions_ to skip parameter types: https://github.com/gajus/eslint-plugin-flowtype/commit/265a3483c660e3e99c1bf14a08dfc6e5200fcdb0
* can use `{ "excludeArrowFunctions": "expressionsOnly" }` on param types
* docs: https://github.com/gajus/eslint-plugin-flowtype/commit/685d73cc708 …
=> Skip Arrow Return Types & option for expressions only

README.md, src/rules/spaceBeforeTypeColon.js, tests/rules/assertions/spaceAfterTypeColon.js, tests/rules/assertions/spaceBeforeTypeColon.js
Noticed that destructuring in a function parameter wouldn't report correctly.
=> Fix Destructuring with spaceBeforeTypeColon

.README/README.md, .README/rules/valid-syntax.md, README.md, src/index.js, src/rules/validSyntax.js, tests/rules/assertions/validSyntax.js, tests/rules/index.js
See #43.
It definitely works, but I'd understand if creating this rule doesn't fit your vision of the project.
I named it that way so we could add other syntax checks to it should we need to.
=> Fix #43: Check for a basic flow syntax error; prevents crashing

README.md, src/rules/spaceAfterTypeColon.js, src/rules/spaceBeforeTypeColon.js, src/utilities/getParameterName.js, tests/rules/assertions/requireReturnType.js, tests/rules/assertions/spaceAfterTypeColon.js, tests/rules/assertions/spaceBeforeTypeColon.js
Extends the existing `spaceAfterTypeColon` and `spaceBeforeTypeColon` rules to apply to type objects, and also to class properties like:
```js
type Foo = { name: string }
const x: { name: string } = { name: 'Dan' }
class Foo { name: ?string }
```
Probably best to view the [first three commits](https://github.com/gajus/eslint-plugin-flowtype/compare/8a96d6a...abf05b43f896106ade14dcadc9a7b71f7f1e8c21) and then the [final commit](https://github.com/gajus/eslint-plugin-flowtype/commit/23f19989bb0946dc332e12a134b96c0998db5ad8) separately. The final commit refactors the result of the previous commits to share code between the function param evaluator and class property evaluator. [Final source](https://github.com/gajus/eslint-plugin-flowtype/blob/23f19989bb0946dc332e12a134b96c0998db5ad8/src/rule …
=> Object & Class Type Spacing

src/utilities/getParameterName.js, tests/rules/assertions/spaceBeforeTypeColon.js
We just encountered an error where the rule was throwing on non-Flow file because it didn't understand how to display a name for it (as it works that out before it evaluates the code)
two changes:
1. added support for destructuring where the right-side is a "MemberExpression": `class X { foo({ bar }: Props = this.props) {} }`
2. don't throw when we can't evaluate a name for the parameter, just provide "Unknown signature" as the name
=> Handle unknown syntax

src/rules/requireParameterType.js, src/rules/spaceAfterTypeColon.js, src/rules/spaceBeforeTypeColon.js, src/rules/validSyntax.js, src/utilities/getParameterName.js, src/utilities/index.js, src/utilities/quoteName.js
Continuing from #65.
When a parameter name can't be determined (because the specific syntax hasn't yet been accounted for), currently it'll throw an error which bubbles up to this message to the user:
Instead, I propose it should just skip the name in the message.
(In the previous PR I was just returning a fallback string which wasn't too nice. Instead it's now returning `null`, and I've handled that case in each error message)
=> "Unknown function signature" in messages

src/rules/spaceAfterTypeColon.js, tests/rules/assertions/spaceAfterTypeColon.js, tests/rules/assertions/spaceBeforeTypeColon.js
Fixes #71
The first two commits here just re-structure the "spacing" tests to keep valid/invalid rules for each supported node type together. So when adding support for a certain syntax (like the next commits do), it's grouped together.
Second two commits are the fixes.
=> Fix parens in type aliases in space-after-colon

.README/rules/require-parameter-type.md, .README/rules/require-return-type.md, README.md
just the clarification part of #59, i don't feel there's much value yet in renaming the value.
=> Clarify excludeArrowFunction option in docs

src/rules/requireValidFileAnnotation.js, src/utilities/isFlowFileAnnotation.js, tests/rules/assertions/requireValidFileAnnotation.js
See https://flowtype.org/blog/2015/12/01/Version-0.19.0.html#noflow
It's nice to not error on this so you explicitly exclude a file, but still require that every file is opted in or out.
=> Add support for @noflow to require-valid-file-annotation.

.README/README.md, .README/rules/space-before-generic-bracket.md, README.md, src/index.js, src/rules/spaceBeforeGenericBracket.js, tests/rules/assertions/spaceBeforeGenericBracket.js, tests/rules/index.js
`space-before-generic-bracket` to enforce spacing before a generic type annotation parameter bracket, defaulting to "never" (no spacing)
e.g. `Promise <string>` vs `Promise<string>`
(first commit updates the readme from previous changes which missed it, second commit is the actual changes)
=> New rule: Space before generic type annotation bracket

.README/README.md, .README/rules/union-intersection-spacing.md, README.md, src/index.js, src/rules/unionIntersectionSpacing.js, tests/rules/assertions/unionIntersectionSpacing.js, tests/rules/index.js
`union-intersection-spacing`
e.g. `string | number` vs `string|number`
not enforcing against multiple spaces so that it allows multi-line unions like:
```
type X =
| string
| number
```
=> new rule: union & intersection spacing

.README/README.md, .README/rules/generic-spacing.md, README.md, src/index.js, src/rules/genericSpacing.js, tests/rules/assertions/genericSpacing.js, tests/rules/index.js
`generic-spacing` to enforce spacing around generic type annotation parameters, defaulting to "never" (no spacing)
e.g. `Promise<string>` vs `Promise< string >`
=> New rule: spacing around generic type annotation parameters

src/rules/spaceAfterTypeColon.js, tests/rules/assertions/spaceAfterTypeColon.js
Fixes #85 
So both these examples produce the same AST, except for the start/end ranges on the nodes
```js
type X = {
foo(): A;
}
type X = {
foo: () => A;
}
```
The first case shouldn't apply `spaceAfterTypeColon` to the ObjectTypeProperty as there is no colon. Differentiating them is easy as the first case's ObjectTypeProperty & FunctionTypeAnnotation span the same range.
=> fix short style function in ObjectTypeProperty

.README/rules/type-id-match.md, src/rules/typeIdMatch.js, tests/rules/assertions/typeIdMatch.js
Changes the default regular expression used to verify the names
of declared types. Previously, patterns with uppercase sequences
(e.g. `MyABCType`) produced errors, hence disallow the use of
acronyms in types (e.g. `CRM`).
ref https://github.com/gajus/eslint-plugin-flowtype/issues/92
=> Allow uppercase sequences in `type-id-match`

.README/README.md, .README/rules/no-weak-types.md, src/index.js, src/rules/noWeakTypes.js, tests/rules/assertions/noWeakTypes.js, tests/rules/index.js
Warns when using weak type annotations **any**, **Object** and **Function**
=> Add new rule for warning against use of weak types

.README/rules/no-weak-types.md, src/rules/noWeakTypes.js, tests/rules/assertions/noWeakTypes.js
e.g. I'd like to initially prevent the "easier" types (`Object` and `Function`), and later start disabling `any`.
This allows me to configure which rules to enable:
```js
{
any: false,
Object: true,
Function: true
}
```
to disable the `any` check, while keeping the `Object` and `Function` checks
_although I can't decide if that reads more as "disallow `any` types, allow `Object`/`Function` types" - the opposite_
=> feat: options to prevent specific types in `noWeakTypes`

.README/README.md, .README/rules/delimiter-dangle.md, src/index.js, src/rules/delimiterDangle.js, tests/rules/assertions/delimiterDangle.js, tests/rules/index.js
See https://github.com/gajus/eslint-plugin-flowtype/issues/40
Trailing delimiters in `ObjectTypeAnnotation` and `TupleTypeAnnotation`.
To mirror ESLint's `comma-dangle` rule, it has the following options: `never` (default), `always`, `always-multiline`, `only-multiline`.
For the multiline rules, I'm pretty sure I'm correctly mirroring the logic of `comma-dangle` - it's multiline if the last property & closing brace are on separate lines.
For `ObjectTypeAnnotation`, I haven't added in the option of comma vs semi-colon. Another rule can handle that (hopefully the one from `eslint-plugin-babel`)
=> feat: add `delimiter-dangle` for trailing commas/semicolons

package.json, src/configs/recommended.json, src/index.js
* Reverts eedcac762eae38cf6030a0b816b86dcb0a2fdfd3.
* Add JSON configuration formatting to a precommit hook.
=> Use JSON config for exported configuration

src/rules/spaceAfterTypeColon.js, src/rules/spaceBeforeTypeColon.js, src/utilities/spacingFixers.js, tests/rules/assertions/spaceAfterTypeColon.js, tests/rules/assertions/spaceBeforeTypeColon.js
For #114.
Leaving open as a PR for a few days while I make sure there's no edge cases to be covered, but I don't think there are.
**Edit:** parens need to be accounted for.. `((x): string)`
=> feat: check TypeCastExpressions in type colon spacing rules

.README/rules/valid-syntax.md, tests/rules/assertions/validSyntax.js
Removed the "invalid" tests as they fail in the parser now.
May want to add an actual deprecation notice as a `console.log`, like this: https://github.com/yannickcr/eslint-plugin-react/blob/6a94967e9fe9dd97bf88244489f672ebe549605d/lib/rules/wrap-multilines.js#L45-L54
=> Deprecate `validSyntax`, Babylon has been fixed

.README/rules/require-valid-file-annotation.md, src/rules/requireValidFileAnnotation.js, tests/rules/assertions/requireValidFileAnnotation.js
This PR adds an option to `require-valid-file-annotation` that allows enforcement of an annotation style (default: none) for files.
=> feat: add annotation enforcement option (fixes #126)

.README/README.md, .README/rules/object-type-delimiter.md, src/index.js, src/rules/objectTypeDelimiter.js, tests/rules/assertions/objectTypeDelimiter.js, tests/rules/index.js
Ported from [`babel/flow-object-type`](https://github.com/babel/eslint-plugin-babel).
See #40, https://github.com/babel/eslint-plugin-babel/issues/93.
I did make one change though: I've changed the default from `semicolon` to `comma` - it seems to be much more common.
=> feat: add object-type-delimiter rule

src/rules/objectTypeDelimiter.js, tests/rules/assertions/objectTypeDelimiter.js
I could not figure out how to rebuild the documentation, and had to `git commit --no-verify`. I would love to contribute more to this project, but the setup is so complicated and it's not very debug friendly :(
=> Support dynamic accessors and callable objects in object-type-delimiter

.README/rules/require-parameter-type.md, src/rules/requireParameterType.js, tests/rules/assertions/requireParameterType.js
This adds the ability to include an option - `excludeParameterMatch` - that takes a regex of parameters to ignore.
This solves the same need as #17/#18, but is (in my opinion) a bit more flexible. (Also, there was no activity on that PR for a few months and I want this ;) )
Closes #17 
Closes #18
=> feat: Add excludeParameterMatch option to require-parameter-type

src/index.js, src/rules/noPrimitiveConstructorTypes.js, tests/rules/assertions/noPrimitiveConstructorTypes.js, tests/rules/index.js
This PR adds a rule that discourages the use of `Number`, `Boolean`, and `String` constructor types in favor of their primitive type counterparts.
Good: `type x = number`
Bad: `type x = Number`
From flowtype docs:
> Note that number and Number are separate types. The former is the type of primitive numbers which appear in programs as literals, like 3.14 and 42, or as the result of expressions like parseFloat(input.value). The latter is the type of Number wrapper objects, which are rarely used.
[More info on primitive types](https://flowtype.org/docs/builtins.html)
=> feat: add no-primitive-constructor-types rule

.README/rules/require-variable-type.md, src/index.js, src/rules/requireVariableType.js, tests/rules/assertions/requireVariableType.js, tests/rules/index.js
This adds a rule that enforces types for all variable declarations.
It has options to ignore declarations based on type (`var`, `let`, or `const`) and based on identifier name (works the same way as what was added to `require-paramter-type` in #143)
Closes #19 
Edit: Let me know if I should squash my commits. It felt cleaner to have them separate, but it's up to you. :)
=>  Add rule for requiring variable type

src/rules/requireValidFileAnnotation.js, src/utilities/fuzzyStringMatch.js, src/utilities/index.js, src/utilities/isFlowFile.js, tests/rules/assertions/requireValidFileAnnotation.js
This PR updates the `requireValidFileAnnotation` rule to include a rudimentary spellcheck for flow like annotations (#106).
I've also added better `@noflow` support which might help address #128.
=> fix: annotation spell check, better @noflow support (fixes #106)

src/rules/validSyntax.js
This PR adds the `deprecated` property to the exported rule object (#152).
=> chore: deprecate valid syntax rule

src/rules/requireReturnType.js, tests/rules/assertions/requireReturnType.js
Top level `return` statement lead to unhandled exception where `targetNodes` is empty array.
```
TypeError: Cannot set property 'returnStatementNode' of undefined
at EventEmitter.ReturnStatement (src/rules/requireReturnType.js:71:7)
at NodeEventGenerator.enterNode (node_modules/eslint/lib/util/node-event-generator.js:40:22)
at CodePathAnalyzer.enterNode (node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
at CommentEventGenerator.enterNode (node_modules/eslint/lib/util/comment-event-generator.js:97:23)
at Controller.enter (node_modules/eslint/lib/eslint.js:928:36)
at Controller.__execute (node_modules/estraverse/estraverse.js:397:31)
at Controller.traverse (node_modules/estraverse/estraverse.js:501:28)
at Controller.Traverser.controller.traverse …
```
=> fix: require-return-type exception

.README/rules/require-return-type.md, src/rules/requireReturnType.js, tests/rules/assertions/requireReturnType.js
This PR addresses #149 - adding the ability to include and exclude functions by name or regex patterns to the `require-return-type` rule.
Ex:
```js
{
"rules": {
"flowtype/require-return-type": [
2,
"always",
{
"includeOnlyMatching": [
"Ba(r|z)"
]
}
]
}
}
{
"rules": {
"flowtype/require-return-type": [
2,
"always",
{
"excludeMatching": [
"^F.*",
]
}
]
}
}
```
=> feat: `require-return-type` include / exclude filter support (fixes #149)

package.json, src/rules/typeColonSpacing/reporter.js
Something changed between ESLint 3.15.0 and 3.16.0 that caused the token to no longer return. It now returns null, instead of a valid token that had a `value !== ':'`.
This adds a check to make sure that `colon` is not null first.
Could possibly be this refactor: https://github.com/eslint/eslint/commit/834f45d32ed322940dd185a32e5342193fdde914
This fixed #196 as well.
=> fix: Ensure colon is not null in typeColonSpacing reporter

package.json
- https://github.com/eslint/eslint/blob/master/package.json#L119
- https://github.com/babel/babel-eslint/blob/master/package.json#L34
=> fix engines

src/rules/noDupeKeys.js, tests/rules/assertions/noDupeKeys.js
Addresses #133 by validating a complex class structure with multiple methods and different keys.
=> fix: no-dupe-keys with legal duplicated keys (fixes #133)

README.md
Following of #228, where I forgot to update the Readme... (no cookies).
=> docs: update no-types-missing-file-annotation case samples

src/rules/requireValidFileAnnotation.js, tests/rules/assertions/requireValidFileAnnotation.js
The `looksLikeFlowFileAnnotation` regex was too broad and would catch
jsdoc comments like `@fixable` and `@function`, causing eslint errors
in projects that don't use flow (in my case).
I updated the regex to only check for anything beginning with
`@flo`. Is there any reason not to full on match `@flow`? I'm not
familiar with how flow works.
This should fix #165.
=> Update `looksLikeFlowFileAnnotation` regex to match only @flow

src/utilities/isFlowFile.js, tests/rules/assertions/noTypesMissingFileAnnotation.js
`eslint-plugin-flowtype` rules require that the `// @flow` comment be the first line of a file.
This is stricter than [Flow requires](https://flow.org/en/docs/usage/#toc-prepare-your-code-for-flow) (emphasis in original), which simply requires the comment appear before any code:
> The Flow background process monitors all Flow files. However, how does it know which files are Flow files and, thus, should be checked? Placing the following **before any code** in a JavaScript file is the flag the process uses to answer that question.
> 
> `1 // @flow`
This PR updates `noTypesMissingFileAnnotation` to allows a comment to appear before the `@flow` comment.
This likely has more implications for `requireValidFileAnnotation`, however.
=> [Request For Comments] fix: @flow flag does not need to be first comment

src/rules/typeColonSpacing/reporter.js, src/utilities/spacingFixers.js, tests/rules/assertions/spaceAfterTypeColon.js
Previously, there was no explicit check for line breaks, and getSpaces
would count line breaks as spaces. That meant that if there only was a
line break between the colon and the type (the first of then new test
cases), the rule would pass even if allowLineBreak was false.
Now it checks if there is a line break between the colon and the type,
and handles that explicitly so it passes if allowLineBreak is true and
fails otherwise.
=> fix: Properly check line breaks in space-after-type-colon

.README/README.md, .README/rules/no-unused-expressions.md, src/index.js, src/rules/noUnusedExpressions.js, tests/rules/assertions/noUnusedExpressions.js, tests/rules/index.js
This rule extends the ESLint's `no-unused-expressions` to ignore type cast expressions.
ESLint's `no-unused-expressions` catches some likely mistakes, but it also complains about bare type cast expressions. These are unlikely to be mistakes and are useful in several situations. See `.README/rules/no-unused-expressions.md` for an example.
=> feat: add rule no-unused-expressions

bin/readmeAssertions.js, package.json
Fixes #276. I placed settings comment below options and above code snippet. I can change the placement if requested.
=> docs: Handle settings property in readmeAssertions.js script

README.md, src/rules/sortKeys.js, tests/rules/assertions/sortKeys.js
This adds an option to `--fix` the `sort-keys` rule.
It would be much cleaner using ESLint v4, because multiple tokens can be replaced. However, this is a fairly good (imo) solution, and it tries hard to maintain code style.
edit: ~this currently does not work in a few cases. Namely, `a: (param: number) => void` (or any function type). It also *doesn't* maintain the `?` in `a?: Object`.~
Alright, I think that covers all the use-cases now. If you can think of any more, please let me know.
Fixes: https://github.com/gajus/eslint-plugin-flowtype/issues/212
=> add an auto-fix option to sortKeys

.README/rules/sort-keys.md, src/rules/sortKeys.js, tests/rules/assertions/sortKeys.js
The fix was accidentally merged (#273) while there were still some issues with it.
The outstanding issues have now been fixed - if there are other things I've overlooked, please let me know.
I'm not convinced on the recursive structure, but it's the only way (I know of) to apply the nested fixes - otherwise they'll just continually conflict.
cc @gajus
=> Fix some issues with the sortKeys autoFix

src/rules/requireReturnType.js, tests/rules/assertions/requireReturnType.js
Fixes #281. In fixing this I realised that class methods as a whole could not be matched by the `excludeMatching`.
=> allow class methods to be excluded from require-return-type

CONTRIBUTING.md, src/rules/defineFlowType.js, tests/rules/assertions/defineFlowType.js
We weren't covering the `declare` versions of Flow type/interface declarations:
declare type Foo = 'foo';
declare interface Foo {};
=> feat: Implement define-flow-type for declare type

README.md, src/rules/defineFlowType.js, tests/rules/assertions/defineFlowType.js
This PR fixes #260 by suppressing invalid `no-undef` warnings when `define-flow-type` is active.
It seems like there's some upstream problems with opaque types causing `opaque type A = Array` to report `A` as `no-undef`, even though it shouldn't. Does anyone happen to have an idea as to which piece of this dependency graph would be responsible for fixing that?
=> fix: Mark opaque type identifiers as defined with define-flow-type

.README/README.md, .README/rules/no-flow-fix-me-comments.md, src/index.js, src/rules/noFlowFixMeComments.js, tests/rules/assertions/noFlowFixMeComments.js, tests/rules/index.js
We use this lint rule internally at Facebook to make sure we keep an eye on these flow suppression comments and ensure they get fixed over time. We figure this might be useful to others as well.
cc @bestander
=> feat: add no-flow-fix-me-comments

src/rules/requireReturnType.js, tests/rules/assertions/requireReturnType.js
Fixes the bug with arrow functions as method properties not being excluded (#217)
=> fix: require-return-type excludeMatching for class properties (#217)

.README/README.md, .README/rules/require-exact-type.md, CONTRIBUTING.md, README.md, src/index.js, src/rules/requireExactType.js, tests/rules/assertions/requireExactType.js, tests/rules/index.js
Adds support for enforcing exact object types.
=> feat: add require-exact-type rule (fixes #304)

.README/README.md, .README/rules/newline-after-flow-annotation.md, src/index.js, src/rules/newlineAfterFlowAnnotation.js, tests/rules/assertions/newlineAfterFlowAnnotation.js, tests/rules/index.js
This checks for an empty line after the `@flow` annotation. It supports three options:
- `"always"`
- `"always-windows"`: Use `\r\n ` to insert line breaks when fixing
- `never`
=> feat: Add newline-after-flow-annotation rule

.README/README.md, .README/rules/no-existential-type.md, src/index.js, src/rules/noExistentialType.js, tests/rules/assertions/noExistentialType.js
This ensures that the existential type (`*`) is not used. This is valuable in large codebases with developers unfamiliar with Flow; it's easily misinterpreted and misused.
Due to differences in flow/babylon[0], there are two potential node names.
[0] https://github.com/babel/babylon/issues/319
=> feat: Add no-existential-type rule

.README/README.md, .README/rules/require-types-at-top.md, src/index.js, src/rules/requireTypesAtTop.js, tests/rules/assertions/requireTypesAtTop.js, tests/rules/index.js
Implements rule requested in #168, #285.
The order of imports and types is not enforced, i.e. having import declarations after type declarations is valid, because I think this should be handled in another rule.
=> feat: Add require-types-at-top rule

.README/README.md, .README/rules/type-import-style.md, src/index.js, src/rules/typeImportStyle.js, tests/rules/assertions/typeImportStyle.js, tests/rules/index.js
Adds a lint rule that discriminates between two import styles:
```
import type {T, U, V} from 'foo';
import {type T, type U, type V} from 'foo';
```
The latter is superior because it's easier to edit/refactor (adding non-type import entries doesn't require changing the entire line import statement).
=> feat: Add type-import-style rule

src/rules/typeImportStyle.js, tests/rules/assertions/typeImportStyle.js
Fixes a bug in `type-import-style`'s fixer that would drop import aliases. For example:
```jsx
import type {A as B} from 'foo';
```
would be fixed to
```jsx
import type {B} from 'foo';
```
I also fixed it to handle default type imports:
```jsx
import type A from 'foo';
```
=> fix: (type-import-style) Support import aliases when fixing

src/rules/noDupeKeys.js
The [new object type spread](https://github.com/facebook/flow/issues/1326) features in Flow cause the noDupeKeys rule to crash. Specifically, `.value` is accessed on the `ObjectTypeSpreadProperty` node, which doesn't have that field.
```javascript
type Foo = {...Bar}; // this would crash noDupeKeyes
```
The workaround is to use the Flow commenting syntax, like this:
/**
type Foo = {...Bar};
*/
I'd love to write tests (and had, in fact), but due to some combination of babylon, babel-eslint, and babel-cli, the object type spread syntax wasn't recognized and would fail tests (most immediately caused by babel-eslint). I tried bumping versions, but ended up going down a bit of a rabbit hole because other tests began failing. Seems like a general version bump refresh is in order.
Would …
=> fix: noDupeKeys ignores ObjectTypeSpreadProperty

package-lock.json, src/rules/sortKeys.js
fixes: #287 
this allows us to run `eslint --fix` on types that have `ObjectTypeSpreadProperty`:
```js
declare export type CoolType = {
...SomeType,
...SomeOtherType,
someOtherProperty: boolean,
someProperty: boolean,
}
```
=> fix: support fixing sort keys with ObjectTypeSpreadProperty

.README/rules/no-mutable-array.md, src/rules/noMutableArray.js, tests/rules/assertions/noMutableArray.js
=> Don't require $ReadOnlyArray if variable is initialized with empty array

src/rules/noFlowFixMeComments.js
Eslint [stopped](https://eslint.org/docs/user-guide/migrating-to-4.0.0#event-comments) to emit `LineComment` and `BlockComment` events in v4.
=> Fix $FlowFixMe comments for eslint 4

src/rules/sortKeys.js, tests/rules/assertions/sortKeys.js
In [Babel parser v7](https://github.com/babel/babel/blob/master/packages/babel-parser/ast/spec.md#babelparser-babylon-v7) the variance is represented as a node instead of a string. Fixes #334. Relates to #336.
I also spotted `ObjectTypeSpreadProperty` case in the rule, but no tests for it. It perhaps relates to Flow's [type extensions](https://github.com/facebook/flow/pull/5973):
```
type One = {| foo: number |};
type Two = {| bar: boolean |};
type Both = {| ...One, ...Two |}
```
So before this is merged, we should probably define how these spread types behave (it is not mentioned in docs), then validate if they work as we want, and if not, fix them.
My proposal is to have them below normal properties if asc is used, i.e.:
```
type Foo = {
z: number,
...Bar,
}
```
=> Fix variance issues with babel 7

src/rules/objectTypeDelimiter.js
Using babel-eslint 8.2.1, the object-type-delimeter rule does nothing, apparently because the `ObjectType{CallProperty,Indexer,Property}` nodes no longer contain trailing semicolons/commas, but their parent `ObjectTypeAnnotation` nodes do.
I could not find a changelog or git commit entry in any of the associated projects for where/why this was changed...
I tried to keep compatibility with both cases, because it's not clear what version this project is targeting. However, I don't know of a good way to test the new behavior given the version of babel-eslint now locked in devDependencies.
=> fix: object-type-delimeter with new babel-eslint

src/rules/requireExactType.js, tests/rules/assertions/requireExactType.js
When indexers are used to create Object Map types, it does not normally make sense for them to be exact (see [here](https://github.com/facebook/flow/issues/3162)).
With `require-exact-type` enabled you end up with lots of `eslint-ignore` comments.
I think it would be better to ignore types with indexers in this rule.
=> fix: make require-exact-type ignore indexers in map types

src/rules/semi.js, tests/rules/assertions/semi.js
Docs for this rule speak about type aliases but I take opaque types just as a bit different type aliases so I didn't change the docs. If I should explicitly mention that this rule works for type aliases *and* opaque types, let me know.
=> Fix semi rule for opaque types

README.md, src/rules/noWeakTypes.js, tests/rules/assertions/noWeakTypes.js
Fixes https://github.com/gajus/eslint-plugin-flowtype/issues/361
=> Add mixed to no-weak-types

.README/rules/require-compound-type-alias.md, src/index.js, src/rules/requireCompoundTypeAlias.js, tests/rules/assertions/requireCompoundTypeAlias.js, tests/rules/index.js
I added a rule which enforces to use type aliases for union and intersection types. I found myself that when I use them in their "raw" or "explicit" (or how to call it?) form I ended up with copy&pasting them all over the code where they were needed. This was true especially when I didn't know they will be needed somewhere else first and this requirement came afterwards. I know that not using copy&paste of code is kind of developer's responsibility and elementary "skill" but laziness sometimes wins.
The name of the rule can be discussed. We have already `union-intersection-spacing` rule so using *compound type* phrase is a little inconsistency. Also I don't know if it is clear what is meant by compound type for the first look.
=> feat: Add require-compound-type-alias

.README/README.md, .README/rules/require-compound-type-alias.md
I apologize but I didn't add the docs of the rule to the readme. I should have tried to generate the docs locally...
=> docs: Add docs about require-compound-type-alias to readme

.README/rules/no-flow-fix-me-comments.md, .README/rules/require-types-at-top.md, .README/rules/valid-syntax.md, CONTRIBUTING.md, README.md, bin/testsAndDocsCheck.js, package.json, tests/rules/index.js
This PR adds a script that checks if there are tests and docs for each rule and they are included in their corresponding "index" files. It was discussed in #366. What exactly is checked is documented in the header of the script. I added this check to pre-commit hook.
Thanks to this script I discovered that three rules have no assertions in readme and that for one rule tests were not executed. I fixed these issues.
Side note: The new post-commit hook crashes when the current branch is not in `.git/config` yet, which I think is before the push to a remote server. This crash comes from gitdown and transitively from gitinfo. Also in [contributing guide](https://github.com/gajus/eslint-plugin-flowtype/blob/200868729916286e711347877fbef76b25d7b5e0/CONTRIBUTING.md) there is a sentence that the …
=> Tests docs check script

.README/README.md, .README/rules/no-mixed.md, README.md, src/configs/recommended.json, src/index.js, src/rules/noMixed.js, tests/rules/assertions/noMixed.js, tests/rules/index.js
Add no-mixed rule. Follow-up to #362
=> Add no-mixed rule

src/configs/recommended.json
The [documentation](https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules) states that the rule `flowtype/valid-syntax` is deprecated since Babylon (the Babel parser) v6.10.0 fixes parsing of the invalid syntax this plugin warned against.
=> fix: remove deprecated rule from recommended config

.travis.yml
fix #388 
not sure if you want this yet, but semantic-release is requiring node >= 8.3 and Node 6 will reach end-of-life this April.
=> ci(.travis.yml): remove node 6 build

.README/rules/type-import-style.md, src/rules/typeImportStyle.js, tests/rules/assertions/typeImportStyle.js
The newly added `ignoreTypeDefault` option, lets you avoid cases where the
rule would normally complain for `import type foo from "...";` when in
"identifier" mode. This is desirable because
`import {type default as foo} from '...';` is kinda long, when you would
otherwise prefer `import type foo from '...';`. Also, `type default as foo`
conflicts with `eslint-plugin-import`'s `import/no-named-default`
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-named-default.md
=> feat: add "ignoreTypeDefault" option to "type-import-style"

src/rules/typeImportStyle.js, tests/rules/assertions/typeImportStyle.js
Putting a type specifier in a `declare module` is a syntax error in both Flow and Babel.
See https://github.com/facebook/flow/issues/7609
=> fix: skip type-import-style identifier in "declare module"

.README/README.md, .README/rules/spread-exact-type.md, src/index.js, src/rules/spreadExactType.js, tests/rules/assertions/spreadExactType.js, tests/rules/index.js
This rule will add possibility to enforce spreading only exact object types, that are explicitly exact. 
When object type is not exact and is spread inside other object annotation, it can lead to resulted type to be dependent on the place, where object type was spread. For example, this case, that from first look is invalid https://flow.org/try/#0C4TwDgpgBAygFgQwE4QCYAUkHtJOASwgGcoBeKAbwCgooAbCAOwHNg4AuKRgVwFsAjCEgA0NLgl4RORYEnwtRAXwDcVKqEhQAchADumHEILEylMQmZSufQSLEA6R-GRoDuY0SWqqAYyyMZKFwif04dfWx3QhJyagBICysAciw6VCSlIA
actually doesn't cause any flow errors. 
One of the way to prevent such cases, is to spread only exact object types.
=> feat: add rule to make sure that object type that is spread has exact type

README.md, src/rules/requireReturnType.js, tests/rules/assertions/requireReturnType.js
Fix #395 by reading the correct property path (parent id name) for "Property" nodes. Fixes the use of include and exclude rules on object properties:
```js
const foo = {
// Without this PR the name of this node is "undefined" for include/exclude matching
bar() {
return 42;
},
// Same here
baz: function() {
return 42;
}
}
```
=> Fix return type rule for plain object properties

src/utilities/isFlowFile.js, src/utilities/isFlowFileAnnotation.js, tests/rules/assertions/defineFlowType.js
Instead of looking for a very specfic string in a part of the docblock,
and then checking the entire docblock for "no" (which can show up in
copyrights, or just general comments that may be documenting a file),
actually see if there's a @noflow comment.
=> Parse docblock more robustly for onlyFilesWithFlowAnnotation usage

src/rules/arrayStyle/index.js, tests/rules/assertions/arrayStyleSimpleType.js
While these are disallowed in Flow, `typeof Array` is a valid type,
which could trigger this.
Rather than try to enumerate other possible cases, I simply check to
make sure we don't crash when we hit them.
=> Don't crash when encountering unparameterized Arrays

.README/README.md, README.md, src/rules/requireReadonlyReactProps.js, tests/rules/assertions/requireReadonlyReactProps.js
- `$FlowFixMe` is ignored
- `{||}` is considered to be read-only
=> Fix requireReadOnlyReactProps

.README/README.md, .README/rules/require-inexact-type.md, .README/rules/require-readonly-react-props.md, README.md, src/index.js, src/rules/requireInexactType.js, tests/rules/assertions/requireInexactType.js, tests/rules/index.js
Duplicate of same lint in new Flow version
This syntax exists from Flow v0.84
=> feat: add require-inexact-type rule

src/rules/noDupeKeys.js, tests/rules/assertions/noDupeKeys.js
Example code:
```js
type a = { b: <C>(config: { ...C, key: string}) => C };
```
Error:
```sh
TypeError: Cannot read property 'type' of undefined
Occurred while linting /Users/hsuting/Desktop/work/core/packages/configs/src/types.js:3
at analizeElement (/Users/hsuting/Desktop/work/core/node_modules/eslint-plugin-flowtype/dist/rules/noDupeKeys.js:29:24)
at /Users/hsuting/Desktop/work/core/node_modules/eslint-plugin-flowtype/dist/rules/noDupeKeys.js:64:21
at arrayMap (/Users/hsuting/Desktop/work/core/node_modules/lodash/lodash.js:639:23)
at Function.map (/Users/hsuting/Desktop/work/core/node_modules/lodash/lodash.js:9556:14)
at builObjectStructure (/Users/hsuting/Desktop/work/core/node_modules/eslint-plugin-flowtype/dist/rules/noDupeKeys.js:63:29)
at analizeElement …
```
=> fix(noDupeKeys): fix throw error

.README/rules/require-valid-file-annotation.md, README.md, src/rules/requireValidFileAnnotation.js, tests/rules/assertions/requireValidFileAnnotation.js
- Added eslint rule for `@flow strict` and its fixer
- Ref, https://github.com/gajus/eslint-plugin-flowtype/issues/364
```js
// Options: ["always",{"annotationStyle":"line","strict":true}]
// @flow
// Message: Strict Flow file annotation is required, should be `// @flow strict`
```
=> Valid flow strict annotation

README.md, src/rules/requireValidFileAnnotation.js, tests/rules/assertions/requireValidFileAnnotation.js
- When use `@noflow`, it won't check strict flow rule now
- Ref, https://github.com/gajus/eslint-plugin-flowtype/pull/414
=> Fix @noflow support for strict

.README/README.md, .README/rules/arrow-parens.md, src/configs/recommended.json, src/index.js, src/rules/arrowParens.js, src/utilities/isFlowFile.js, tests/rules/assertions/arrowParens.js, tests/rules/index.js
This should resolve #344.
I did this quick and dirty, and I'm not sure if it's the correct approach. What I did was:
1. Copied `arrow-parens` rule and tests into `eslint-plugin-flowtype` from `eslint`,
2. Resolved various linting issues and glued code together to work with `eslint-plugin-flowtype` environment,
3. Added tests specific to flow support,
4. Modified behavior of `arrow-parens` rule so that the tests passed.
Let me know if there's a better way to override an eslint rule. Also, I'm not sure if this should go into the recommended config or whatever.
This may also be of interest to https://github.com/typescript-eslint/typescript-eslint/issues/14.
=> Implement arrow-parens to support type parameters

src/rules/arrowParens.js, tests/rules/assertions/arrowParens.js
Found an even smaller corner case for `arrow-parens`. Again, I'm assuming my logic here makes sense. I don't see a case where an arrow function with a predicate could not have parens.
Is `fix:` fine for this or is this a `feat:`?
=> fix: ignore arrow functions with predicates in arrow-parens

.README/README.md, .README/rules/require-indexer-name.md, src/index.js, src/rules/requireIndexerName.js, src/utilities/getParameterName.js, tests/rules/assertions/requireIndexerName.js, tests/rules/index.js
Maybe also add some options to validate name later
=> Add require-indexer-name rule

src/utilities/getParameterName.js, tests/rules/assertions/noDupeKeys.js
Fix #431 
The following code failed because `get` occurs twice (it should instead be comparing function names)
```javascript
export interface Foo {
get foo(): boolean;
get bar(): string;
}
```
**root cause**: the function call `getParameterName(identifierNode, context)` did not take into account that `get` and `set` tokens may occur before the variable name. This PR fixes this.
=> fix: getter and setter for no-dedupe

.README/rules/delimiter-dangle.md, README.md, src/rules/delimiterDangle.js, tests/rules/assertions/delimiterDangle.js
Currently, the `delimiter-dangle` rule either requires or disallows a dangling delimiter for inexact object notation the same as if it were a regular property. Most often, it's preferred not to have a delimiter after the inexact object notation since it must always be at the end of the object. This PR adds an option to the `delimiter-dangle` rule either require or disallow a dangling delimiter specifically for the inexact object notation.
This also fixes a bug where the property before the inexact notation is reported as the location of the error when the error is actually for the inexact notation.
Before:
```js
// Options: ["always-multiline"]
type X = {
foo: string, // Error is (incorrectly) for this property
...
}
```
After:
```js
// Options: ["always-multiline"]
type X = {
foo: …
```
=> feat: support inexact object notation in delimiter-dangle rule

src/rules/sortKeys.js, tests/rules/assertions/sortKeys.js
For the `flowtype/sort-keys` rule:
1. Fixes dropping of spread generic type arguments when keys are reordered.
2. Fixes reordering of spread elements. The order of spreads is significant and must be preserved, sort only standalone keys between the spans of spreads.
3. Fixes comment handling and preservation.
4. Makes it clear in the tests and code comments that the objects within generic type arguments are not auto-fixed even though they show an error (can be fixed later).
I had to reimplement `generateOrderedList` and a part of `generateFix` to get this working to find tokens an replacement ranges more precisely (most difficult were comments). Hope it won't be very hard to review; I recommend reviewing the full code, not the red/green diff lines.
See added tests. Before this PR, the …
=> fix: sort-keys spreads, spreads with generics, comment handling

src/rules/requireValidFileAnnotation.js, tests/rules/assertions/requireValidFileAnnotation.js
This helps to make annotation style consistent gradually when touching files.
=> Add fixer to invalid file annotation style message

.README/rules/require-valid-file-annotation.md, README.md
=> Fix “consistent” typo

src/index.js, src/rules/requireValidFileAnnotation.js, src/utilities/checkFlowFileAnnotation.js, src/utilities/index.js, src/utilities/isNoFlowFile.js, src/utilities/isNoFlowFileAnnotation.js, tests/rules/assertions/requireReturnType.js
Fixes #450 
Added respect to `@noflow` annotation.
Notice: `npm run create-readme` didn't work for me - failed with error `Branch ("master") definition does not exist in the config`
=> Add respect to `@noflow` annotation

src/index.js, src/rules/arrayStyle/index.js, src/rules/booleanStyle.js, src/rules/delimiterDangle.js, src/rules/genericSpacing.js, src/rules/newlineAfterFlowAnnotation.js, src/rules/noMutableArray.js, src/rules/objectTypeDelimiter.js, src/rules/requireIndexerName.js, src/rules/requireReadonlyReactProps.js, src/rules/requireReturnType.js, src/rules/requireValidFileAnnotation.js, src/rules/semi.js, src/rules/sortKeys.js, src/rules/spaceAfterTypeColon.js, src/rules/spaceBeforeGenericBracket.js, src/rules/spaceBeforeTypeColon.js, src/rules/typeImportStyle.js, src/rules/unionIntersectionSpacing.js, src/utilities/checkFlowFileAnnotation.js, src/utilities/fuzzyStringMatch.js
I was going to work on an issue, so I did a fresh clone and an npm install - which installed the latest ESLint version.
The latest version of ESLint RuleTester has a hard requirement that all fixable rules declare `meta.fixable`.
This simply fixes that, and fixes the small number of lint errors that were in the codebase at the same time.
=> fix: annotate fixable rules

src/index.js, src/rules/arrayStyle/index.js, src/rules/booleanStyle.js, src/rules/delimiterDangle.js, src/rules/genericSpacing.js, src/rules/newlineAfterFlowAnnotation.js, src/rules/noMutableArray.js, src/rules/objectTypeDelimiter.js, src/rules/requireIndexerName.js, src/rules/requireReadonlyReactProps.js, src/rules/requireReturnType.js, src/rules/requireValidFileAnnotation.js, src/rules/semi.js, src/rules/sortKeys.js, src/rules/spaceAfterTypeColon.js, src/rules/spaceBeforeGenericBracket.js, src/rules/spaceBeforeTypeColon.js, src/rules/typeImportStyle.js, src/rules/unionIntersectionSpacing.js, src/utilities/checkFlowFileAnnotation.js, src/utilities/fuzzyStringMatch.js, tests/rules/assertions/sortKeys.js
Fixes #455
This PR is based on top of #458, and should only be merged *after* that one.
If you wanted to just merge one PR, then the two commits are separated appropriately.
=> fix: [sort-keys] handle method signatures

.README/README.md, .README/rules/object-type-curly-spacing.md, README.md, src/index.js, src/rules/objectTypeCurlySpacing.js, tests/rules/assertions/objectTypeCurlySpacing.js, tests/rules/index.js
Added new rule `objectTypeCurlySpacing`  that enforces consistent spacing inside braces of object types.
Options: never (default) or always
Never (default)
```
// Correct
type Y = {foo: "bar"};
// Incorrect
type N = { foo: "bar" };
```
Always
```
// Options: ["always"]
// Correct
type Y = { foo: "bar" };
// Incorrect
type N = {foo: "bar"};
type Z = {foo: "bar" };
type X = { foo: "bar"};
```
@gajus 
Note: 
Closes #146
=> feat: Added rule objectTypeCurlySpacing

README.md, src/rules/objectTypeCurlySpacing.js, tests/rules/assertions/objectTypeCurlySpacing.js
Fix errors where on `options: ["always"]` the rule threw errors when there was more than 1 space present from the first and last tokens. 
```
// Options: ["always"] 
type z = {
foo: "bar",
raz: "yar",
};
```
@gajus
=> fix: object-type-curly-spacing should not throw errors on multiple spaces on option always 

.README/README.md, .README/rules/no-internal-flow-type.md, src/index.js, src/rules/noInternalFlowType.js, tests/rules/assertions/noInternalFlowType.js, tests/rules/index.js
This commit adds a new rule 'no-internal-flow-type' originally developed and used here: https://github.com/adeira/universe/blob/ce3a89d0d845a7bf5aa6086adef9493f5e0effda/src/eslint-plugin-adeira/src/rules/no-internal-flow-type.js
It prevents users from using internal Flow types such as `React$Node` and suggests public Flow types such as `React.Node` instead.
=> feat: migrate a new rule 'no-internal-flow-type'

CONTRIBUTING.md, README.md, tests/rules/assertions/noInternalFlowType.js
Followup after https://github.com/gajus/eslint-plugin-flowtype/commit/fd838c3dce0e5917d7a26ed8074645b2d510cd68
I didn't generate the docs because I misunderstood the contribution guide. This commit fixes it and updates the contribution guide a little bit.
=> docs: regenerate README.md

.README/rules/require-readonly-react-props.md, README.md, src/rules/requireReadonlyReactProps.js, tests/rules/assertions/requireReadonlyReactProps.js
This commit adds a support for implicit exact Flow types. This is especially useful when using `exact_by_default=true` Flow option and migrating towards `{ }` and `{ ... }` syntax (Flow standard is now to use `{ }` for strict objects and `{ key: value, ... }` for open objects).
Closes: https://github.com/gajus/eslint-plugin-flowtype/issues/467
TODO:
=> feat: add support for implicit exact Flow types

.README/README.md, .README/rules/use-read-only-spread.md, README.md, src/index.js, src/rules/useReadOnlySpread.js, tests/rules/assertions/useReadOnlySpread.js, tests/rules/index.js
This commit adds a new rule 'use-read-only-spread' originally developed and used in [`adeira/universe`](https://github.com/adeira/universe/blob/91ba39d4f59ac0376121b67e443f474a6ade4feb/src/eslint-plugin-adeira/src/rules/flow-use-readonly-spread.js).
It prevents users from accidentally creating an object which is no longer read-only because of Flow spread operator.
TODO:
=> feat: migrate a new rule 'use-read-only-spread'

src/rules/requireReadonlyReactProps.js, tests/rules/assertions/requireReadonlyReactProps.js
Example from our repo before this change:
```
error: Props must be $ReadOnly (flowtype/require-readonly-react-props) at src/kochka.com.mx/src/Layout.js:39:7:
37 |   return (
38 |     <>
> 39 |       <Head>
|       ^
40 |         <title>KOCHKA café · {props.title}</title>
41 |       </Head>
42 |
```
As you can see the error seems to be wrongly positioned. This is even more awkward when you want to suppress this error (and you have to do it on some unrelated line).
After this fix:
```
error: Props must be $ReadOnly (flowtype/require-readonly-react-props) at src/kochka.com.mx/src/Layout.js:28:39:
26 |     };
27 |
> 28 | export default function Layout(props: Props): React.Node {
|                                       ^
29 |   if (props.withHiddenTitle === true) {
30 | …
```
=> fix: fix read-only React props error position

.README/rules/require-readonly-react-props.md, README.md, src/rules/requireReadonlyReactProps.js, tests/rules/assertions/requireReadonlyReactProps.js
This change fixes the following (simplified) example from our application:
```
type Props =
| {
+children: React$Node,
+title: React$Node,
+withHiddenTitle?: false,
}
| {
+children: React$Node,
+title?: React$Node,
+withHiddenTitle: true,
};
const props: Props = {children:"", withHiddenTitle: true}
props.title = ""; // correct Flow error
```
Flow correctly throws the following error:
```
14: props.title = "";
^ Cannot assign empty string to `props.title` because property `title` is not writable. [cannot-write]
```
However, `flowtype/require-readonly-react-props` Eslint rule throws the following (incorrect) error:
```
Props must be $ReadOnly
```
For simplification, all of the objects in the union must be readonly even though it's probably not a strict requirement in Flow. This can be …
=> fix: support union type in React react-only props rule

README.md, src/rules/objectTypeCurlySpacing.js, tests/rules/assertions/objectTypeCurlySpacing.js
closes #480 
`object-type-curly-spacing` does not get triggered when the token and brace are not on the same line.
2 Scenarios: 
-  **opening brace & first token** must be on the same line
- **closing brace & last token** must be on the same line
The following are valid under the `object-type-curly-spacing` rule: 
Option: Never 
```
type bar = {
rew: string,
yup: string,}
type bar = {
rew: string,
yup: string,
}
type bar = {
rew: string,
yup: string,
}
```
Option: Always 
```
type bar = {
rew: string,
yup: string, }
type bar = {
rew: string,
yup: string,
}
type bar = { 
rew: string,
yup: string,
}
```
@gajus
=> fix: object-type-curly-spacing should not trim multi-line expressions

.README/README.md, .README/rules/enforce-line-break.md, README.md, src/index.js, src/rules/enforceLineBreak.js, tests/rules/assertions/enforceLineBreak.js, tests/rules/index.js
New rule to enforce line breaks before and after type declarations.
Closes #476 
```
// Error
type A = string;
type B = number;
// Some Comment
type rez = string;
// Fixes to 
type A = string;
type B = number;
// Some Comment
type rez = string;
```
@gajus
=> feat: add new rule enforce-line-break

src/rules/genericSpacing.js, tests/rules/assertions/genericSpacing.js
The generic-spacing rule doesn't support CRLF line breaks.
```js
// Passes
type X =  Promise<\n    (foo),\n    bar,\n    (((baz)))\n>
// Doesn't pass
type X =  Promise<\r\n    (foo),\r\n    bar,\r\n    (((baz)))\r\n>
```
=> fix: support CRLF line breaks in generic-spacing (#485)

src/rules/enforceLineBreak.js, tests/rules/assertions/enforceLineBreak.js
=> enforceLineBreak now handles `export type` correctly

src/rules/sortKeys.js, tests/rules/assertions/sortKeys.js
what was the issue?
if there is a comment (block/line) in front of the function property, the comment will affect the sorted order of items.
for example, a should be placed in front of b, but b got in front because it's ranked with "/"
```
+ expected - actual
type FooType = {
+          /* preserves block comment before a */
+          a: number | string | boolean,
/* preserves block comment before b */
b(param: string): number,
-          /* preserves block comment before a */
-          a: number | string | boolean,
/* preserves block comment before c */
c: number,
}
```
this PR fix the issue.
=> fix: use name to sort method property

.README/README.md, .README/rules/sort-type-union-intersection-members.md, src/index.js, src/rules/sortTypeUnionIntersectionMembers.js, tests/rules/assertions/sortTypeUnionIntersectionMembers.js, tests/rules/index.js
Adds the sort-type-union-intersection-members rule from typescript-eslint.
It enforces that members of a type union/intersection are sorted alphabetically.
#498
=> feat: add new rule sort-type-union-intersection-members

.README/README.md, .README/rules/no-duplicate-type-union-intersection-members.md, src/index.js, src/rules/noDuplicateTypeUnionIntersectionMembers.js, tests/rules/assertions/noDuplicateTypeUnionIntersectionMembers.js, tests/rules/index.js
Implements new rule proposed for `typescript-eslint` here: https://github.com/typescript-eslint/typescript-eslint/issues/2738
This rule is similar to the `sort-type-union-intersection-members` rule but checks for duplicate members of a type union/intersection.
=> feat: add new rule no-duplicate-type-union-intersection-members

src/configs/recommended.json
In my environment with `eslint` v8.1.0 and `eslint-plugin-flowtype` v8.0.3, `flowtype/recommended` will happens error like below.
```
Oops! Something went wrong! :(
ESLint: 8.1.0
Error: Failed to load parser '@babel/eslint' declared in '.eslintrc.json#overrides[3] » plugin:flowtype/recommended': Cannot find module '@babel/eslint'
```
It cannot omit `parser` suffix on config.
=> fix: recommended config cannot omit "parser"
